@host = http://localhost:5298
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InByb2Zlc3NvcjEiLCJyb2xlIjoic2VuaGExIiwiVXNlclR5cGUiOiJwcm9mZXNzb3IiLCJuYmYiOjE3MjUzMTEwNDMsImV4cCI6MTcyNzk3NTA0MywiaWF0IjoxNzI1MzExMDQzfQ.H9kZSbWmYocmkFc-omp2HW51233a5gw3D4td3IH95jM

###
GET {{host}}/aluno HTTP/1.1
Authorization: Bearer {{token}}

### Post a new professor
POST {{host}}/professor HTTP/1.1
Content-Type: application/json

{
    "IdAcademia": 1,
    "Nome": "João da Silva",
    "Cpf": "987.654.321-00",
    "DtNascimento": "1980-03-15",
    "Login": "professor1",
    "Senha": "senha1"
}

### aluno

POST {{host}}/aluno HTTP/1.1
Content-Type: application/json

{
    "idAcademia": 1,
    "idProfessor": 3,
    "nome": "aluno 4443",
    "cpf": "987.654.321-00",
    "dtNascimento": "1983-03-15",
    "login": "aluno4443",
    "senha": "senha4443"
}
####

GET {{host}}/professor/3 HTTP/1.1

###

POST {{host}}/professor/login HTTP/1.1
Content-Type: application/json

{
    "Login": "professor1",
    "Senha": "senha1"
}
###


POST {{host}}/treino HTTP/1.1
Content-Type: application/json

{
    "IdAluno": 2,
    "Letra": "C",
    "DiaSemana": "Terça-feira",
    "ListaExercicios": "Supino; Agachamento; Flexão; muitos exercicios"
}
