version: '3.8'

services:
  academia_api:
    build:
      context: ./backend/academia_api
    environment:
      # Conectando ao MySQL do computador host via host.docker.internal
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=db_academia;User=root;Password=admin;Port=3306;User=root;Password=admin;
    ports:
      - "5777:5777"
    volumes:
      - ./backend/academia_api:/app
      - /app/bin # Evita problemas com compilação e binários sobrescritos
    restart: always
    
  academia_frontend:
    build:
      context: ./frontend/academia
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://host.docker.internal:5777 # Acessa o backend na máquina host
    depends_on:
      - academia_api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/academia:/app
      - /app/node_modules
    command: yarn dev

# Removido o serviço MySQL do Docker, pois será utilizado o MySQL do host local

volumes:
  mysql-data:
